name: littlemomo
description: "A delicious momo (dumpling) ordering app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  
  # UI packages
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.2
  path: ^1.8.3
  
  # Image handling
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  logger: ^2.5.0
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/momo.jpg
    - assets/veg.webp
    - assets/buff.png
    - assets/fried.jpg
    - assets/spicy.webp
    - assets/paneer.webp
    - assets/ai.jpg  
