name: littlemomo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: 2.14.0
  firebase_auth: 4.6.2
  cloud_firestore: 4.8.0
  firebase_storage: 11.2.2
  
  # UI packages
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  
  # Database
  sqflite: ^2.3.2
  path: ^1.8.3
  
  # Image handling
  image_picker: ^1.0.5
  
  # Utilities
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  logger: ^2.0.1
  google_sign_in: ^6.1.4
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/momo.jpg
    - assets/veg.webp
    - assets/buff.png
    - assets/fried.jpg
    - assets/spicy.webp
    - assets/paneer.webp
    - assets/ai.jpg
    - assets/google.png
