name: littlemomo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.8
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/Logo.webp  # Ensure your image is inside the `assets/` folder
